spring:
  application:
    name: nutrition-tracker-api

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations:
      enabled: true
      locations: classpath:db/migration

server:
  error:
    include-stacktrace: always
