spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: false
logging:
  level:
    com.mournlied.nutrition_tracker_api: DEBUG